### ISSUE TITLE
[EPIC] Review and update

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/docs-security#16]
**Description**
This epic is created to track the review of security docs [1].

**Tasks**
- [ ] Check overall information architecture
- [ ] Review and update <section_1>
- [ ] Review and update <section_2>

**Related links**

[1] https://security.docs.wso2.com/en/latest/
